package com.tsi.tom.williams.demoTest;
// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class ReactUiTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void reactUiTest() {
    driver.get("http://34.239.182.84:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("tr:nth-child(1) .categoryTableRowButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector("tr:nth-child(1) .filmTableButton")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .categoryTableRowButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector("tr:nth-child(1) .filmTableButton")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .categoryTableRowButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector("tr:nth-child(1) .filmTableButton")).click();
    driver.findElement(By.id("footerButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector("ul:nth-child(1) > #footerButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("Selenium");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector("ul:nth-child(2) > #footerButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).sendKeys("Test");
    driver.findElement(By.cssSelector(".form-control:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".form-control:nth-child(4)")).sendKeys("Test");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector("ul:nth-child(3) > #footerButton")).click();
    driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("Test");
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
}
